sudo: required
services:
  - docker

before_install:
  - docker build -t ritusingh/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run ritusingh/react-test npm test -- --coverage

after_success:
  - docker build -t ritusingh/multi-client ./client
  - docker build -t ritusingh/multi-server ./server
  - docker build -t ritusingh/multi-nginx ./nginx
  - docker build -t ritusingh/multi-worker ./worker
  # LOgin to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker-hub
  - docker push ritusingh/multi-client
  - docker push ritusingh/multi-server
  - docker push ritusingh/multi-nginx
  - docker push ritusingh/multi-worker